function [scenario, egoVehicle] = scenario_01_AEB_Bicyclist_Longitudinal_25width()
% scenario_01_AEB_Bicyclist_Longitudinal_25width Returns the
% drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.12 (R2022a) and Automated Driving Toolbox 3.4 (R2022a).

% Copyright 2021 The MathWorks, Inc.

% Construct a drivingScenario object.
scenario = drivingScenario('SampleTime', 0.05,'StopTime', 8.6);

% Add all road segments
roadCenters = [0 0 0;
    1000 0 0];
roadWidth = 10;
road(scenario, roadCenters, roadWidth, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [9 0 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Vehicle Under Test');
waypoints = [9 0 0;
    111 0 0];
speed = 13.89;
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
euroNCAPBicyclistTarget = actor(scenario, ...
    'ClassID', 3, ...
    'Length', 1.9, ...
    'Width', 0.5, ...
    'Height', 1.865, ...
    'Position', [80.4 -0.45 0], ...
    'Mesh', driving.scenario.bicycleMesh, ...
    'Name', 'Euro NCAP Bicyclist Target');
waypoints = [80.4 -0.45 0;
    86.6 -0.45 0;
    114.6 -0.45 0];
speed = [0;5.55;5.55];
trajectory(euroNCAPBicyclistTarget, waypoints, speed);

