function [scenario, egoVehicle] = scenario_04_AEB_CCRb_2_initialGap_12m()
% scenario_04_AEB_CCRb_2_initialGap_12m Returns the drivingScenario defined
% in the Designer

% Generated by MATLAB(R) 9.12 (R2022a) and Automated Driving Toolbox 3.4 (R2022a).

% Copyright 2021 The MathWorks, Inc.

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 8.2, ...
    'SampleTime', 0.05);

% Add all road segments
roadCenters = [0 0 0;
    1000 0 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 10, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [20 0 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Vehicle UnderTest');
waypoints = [20 0 0;
    150 0 0];
speed = 13.89;
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
globalvehicletarget = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [36.7 0 0], ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Global Vehicle Target');
waypoints = [36.7 0 0;
    70 0 0;
    118.23 0 0];
speed = [13.89;13.89;0];
trajectory(globalvehicletarget, waypoints, speed);

